export const TOOL_NAMES = [
  "ChatGPT",
  "GitHub Copilot",
  "Notion AI",
  "Midjourney",
  "Grammarly",
  "Claude",
  "Jasper",
  "Runway",
  "Perplexity",
  "Cursor",
  "Linear AI",
  "Otter.ai",
  "Copy.ai",
  "Writesonic",
  "Synthesia",
  "Descript",
  "ElevenLabs",
  "Zapier AI",
  "Make AI",
  "Other",
]

export const TOOL_PLANS: Record<string, string[]> = {
  ChatGPT: ["Free", "Plus (₹1,650/mo)", "Team (₹2,100/seat)", "Enterprise"],
  "GitHub Copilot": ["Individual (₹830/mo)", "Business (₹1,580/seat)", "Enterprise (₹3,250/seat)"],
  "Notion AI": ["Plus (₹660/mo)", "Business (₹1,250/mo)", "Enterprise"],
  Midjourney: ["Basic (₹830/mo)", "Standard (₹2,500/mo)", "Pro (₹5,000/mo)", "Mega (₹10,000/mo)"],
  Grammarly: ["Free", "Premium (₹1,000/mo)", "Business (₹1,250/seat)"],
  Claude: ["Free", "Pro (₹1,650/mo)", "Team (₹2,100/seat)"],
  Cursor: ["Hobby (Free)", "Pro (₹1,650/mo)", "Business (₹3,300/seat)"],
  Jasper: ["Creator (₹3,250/mo)", "Pro (₹4,900/mo)", "Business"],
  Runway: ["Standard (₹1,000/mo)", "Pro (₹2,300/mo)", "Unlimited (₹6,300/mo)"],
  Perplexity: ["Free", "Pro (₹1,650/mo)"],
  "Linear AI": ["Free", "Basic (₹660/mo)", "Business (₹1,250/seat)"],
  "Otter.ai": ["Basic (Free)", "Pro (₹830/mo)", "Business (₹1,660/seat)"],
  "Copy.ai": ["Free", "Pro (₹3,300/mo)", "Team (₹5,800/mo)"],
  Writesonic: ["Free", "Individual (₹1,600/mo)", "Teams (₹4,100/mo)"],
  Synthesia: ["Starter (₹2,200/mo)", "Creator (₹5,800/mo)", "Enterprise"],
  Descript: ["Free", "Creator (₹1,000/mo)", "Business (₹2,500/mo)"],
  ElevenLabs: ["Free", "Starter (₹830/mo)", "Creator (₹2,500/mo)"],
  "Zapier AI": ["Free", "Professional (₹1,660/mo)", "Team (₹2,500/mo)"],
  "Make AI": ["Free", "Core (₹830/mo)", "Pro (₹1,660/mo)"],
  Other: ["Free", "Starter", "Pro", "Enterprise"],
}

export const USE_CASES = [
  "Code Generation",
  "Writing & Content",
  "Design & Images",
  "Research",
  "Customer Support",
  "Data Analysis",
  "Meetings & Docs",
  "Marketing",
  "HR & Recruiting",
  "Legal & Compliance",
  "Finance & Reporting",
  "Other",
]
